# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lead_v1.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lead_v1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlead_v1.proto\x12\x0btracefabric\"d\n\x07RawLead\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nsource_url\x18\x02 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x03 \x01(\t\x12\x10\n\x08raw_html\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"0\n\tLeadBatch\x12#\n\x05leads\x18\x01 \x03(\x0b\x32\x14.tracefabric.RawLeadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lead_v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RAWLEAD']._serialized_start=30
  _globals['_RAWLEAD']._serialized_end=130
  _globals['_LEADBATCH']._serialized_start=132
  _globals['_LEADBATCH']._serialized_end=180
# @@protoc_insertion_point(module_scope)
